project:
  type: website

website:
  title: "TEAM_What-is-the-dinner-menu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

